services:
    _defaults:
        autowire: true
        public: true

    App\EntityListener\:
        resource: '../../src/EntityListener'
        tags:
            - { name: doctrine.orm.entity_listener }