services:
    admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
        public: true

    admin.turbine:
        class: App\Admin\TurbineAdmin
        arguments: [~, App\Entity\Turbine, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Turbine }
        public: true

    admin.stage:
        class: App\Admin\StageAdmin
        arguments: [~, App\Entity\Stage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Stage }
        public: true