security:
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SUPER_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_EMPLOYEE

        ROLE_EMPLOYEE:
            - ROLE_USER
            - ROLE_ALLOWED_TO_SWITCH

