security:
    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SUPER_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_EMPLOYEE

        ROLE_EMPLOYEE:
            - ROLE_USER
            - ROLE_ALLOWED_TO_SWITCH

            - ROLE_ADMIN_TURBINE_LIST
            - ROLE_ADMIN_TURBINE_VIEW

            - ROLE_ADMIN_PROCESS_LIST
            - ROLE_ADMIN_PROCESS_VIEW

            - ROLE_ADMIN_STAGE_LIST
            - ROLE_ADMIN_STAGE_VIEW

            - ROLE_ADMIN_COMPONENT_LIST
            - ROLE_ADMIN_COMPONENT_VIEW