imports:
    - { resource: security_roles.yaml }

security:
    providers:
        user_provider:
            id: App\Security\Provider\UserProvider

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            anonymous: ~
            form_login:
                provider:      user_provider
                login_path:    admin_login
                check_path:    admin_login
                default_target_path: /admin
                failure_path:  admin_login
            logout:
                path: /admin/logout
                target: /admin/login
            switch_user: true

    access_decision_manager:
        strategy: unanimous

    access_control:
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
