sonata_admin:
    title: 'Winder'
    title_logo: bundles/sonataadmin/windmill_logo.png

    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    security:
        handler: sonata.admin.security.handler.role

        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            IMPORT: IMPORT
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            OPERATOR: OPERATOR
            MASTER: MASTER

    templates:
        layout: layout.html.twig
        user_block: core/user_block.html.twig
        search: '@SonataAdmin/Core/search.html.twig'
        search_result_block: '@SonataAdmin/Block/block_search_result.html.twig'

    global_search:
        empty_boxes: fade

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
