sonata_admin:
    title: 'Winder'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    security:
        handler: sonata.admin.security.handler.role

        information:
            EDIT: EDIT
            LIST: LIST
            CREATE: CREATE
            IMPORT: IMPORT
            VIEW: VIEW
            DELETE: DELETE
            EXPORT: EXPORT
            OPERATOR: OPERATOR
            MASTER: MASTER

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
