version: '3.2'

services:
     mysql:
          image: mysql:5.6
          container_name: winder-mysql
          environment:
              - MYSQL_ROOT_PASSWORD=qwerty
              - MYSQL_DATABASE=winder
              - MYSQL_USER=winder
              - MYSQL_PASSWORD=winder
          ports:
              - 3306:3306

     php-fpm:
        build:
          context: .
          dockerfile: docker/php-fpm/Dockerfile
        container_name: winder-php
        working_dir: /application
        volumes:
              - type: bind
                source: ./
                target: /application
        ports:
              - 7779:8000
